# Generated by Django 5.1 on 2024-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
